# Generated by Django 6.0.1 on 2026-01-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='website',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.RemoveField(
            model_name='productdocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='productdocument',
            name='url',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
